### ISSUE TITLE
jar file

### ISSUE THREAD

**Issue by charga** [equinor/neqsim#150]
The only file I need is the jar file? It contains the GUI or is only the calculation librarie?

Thanks

**Comment by EvenSol** [comment]
Hi.
You find the jar file under releases : https://github.com/equinor/neqsim/releases
The neqsim.jar file only contain the mathematical models.

The simplest way of doing calculations using neqsim, is to look at the examples in Colab that you can run directly in the browser. See:

https://colab.research.google.com/github/EvenSol/NeqSim-Colab/blob/master/notebooks/examples_of_NeqSim_in_Colab.ipynb
