### ISSUE TITLE
calculate properties when total rate is 0

### ISSUE THREAD

**Issue by EvenSol** [equinor/neqsim#195]
Not possible to calculate properties when rate is 0.

**Comment by EvenSol** [comment]
stusset på at tettheten kom ut som 0. Hvis du skal gjøre kodeendringer, er det kanskje heller bedre å se på det litt mer generelt - hva kan man få ut uten rate - altså komposisjonsegenskaper/EOS-egenskaper og lage egen metode for det? Men - ikke noe stress herfra, det ordner seg

**Comment by asmfstatoil** [comment]
It is currently not possible to specify the component fractions when total rate is 0.
