### ISSUE TITLE
Remove NetCDF library dependence

### ISSUE THREAD

**Issue by EvenSol** [equinor/neqsim#445]
**Is your feature request related to a problem? Please describe.**
NeqSim has a dependence for NetCDF for plotting some data related to pipeline transport. However the library is old, and this dependence should be removed.

**Describe the solution you'd like**
Remove dependence from pom.

**Comment by asmfstatoil** [comment]
NB! Visad is also coming from [Unidata UCAR] repository storage.

**Comment by EvenSol** [comment]
> NB! Visad is also coming from [Unidata UCAR] repository storage.

Yes. It world be good to remove the dependency of borg these libraries.
