### ISSUE TITLE
addFluid is not adding PC if not existing. 

### ISSUE THREAD

**Issue by dupuypablo** [equinor/neqsim#684]
So this function should to add PC if PC is not already present. It works well adding components, but not pseudo-components.

https://github.com/equinor/neqsim/blame/29e4944245e8b513b582c97d66b6c1f47b41f475/src/main/java/neqsim/thermo/system/SystemThermo.java#L258

**Comment by EvenSol** [comment]
I have added a test - but this seems to work fine:

```
  @Test
  @DisplayName("test addFluids with pseudo component")
  public void testAddFluids() {

    neqsim.thermo.system.SystemPrEos fluid1 = new neqsim.thermo.system.SystemPrEos(298.0, 10.0);
    fluid1.addComponent("methane", 1.0);
    fluid1.addTBPfraction("C7", 1.0, 0.09, 0.81);
    fluid1.setMixingRule("classic");

    neqsim.thermo.system.SystemPrEos fluid2 = new neqsim.thermo.system.SystemPrEos(298.0, 10.0);
    fluid2.addComponent("methane", 1.0);
    fluid2.addTBPfraction("C7", 1.0, 0.09, 0.81);
    fluid2.setMixingRule("classic");

    fluid1.addFluid(fluid2);

    assertEquals(2.0, fluid1.getComponent(0).getNumberOfmoles());
    assertEquals(2.0, fluid1.getComponent(0).getNumberOfmoles());

    assertEquals(2.0, fluid1.getComponent("methane").getNumberOfmoles());
    assertEquals(2.0, fluid1.getComponent("C7_PC").getNumberOfmoles());
  }
```

**Comment by EvenSol** [comment]
bug found and code updated. The challenge is that a new pseudo component has to be created in the fluid with default methods for calculating properties based on molar mass and liquid density (and we are not sure all properties and parameters are transferred from original fluid).
