### ISSUE TITLE
Performance test as part of build

### ISSUE THREAD

**Issue by EvenSol** [equinor/neqsim#708]
**Is your feature request related to a problem? Please describe.**
Need to make sure updates are not reducing simulation performance. See issue:
#706

**Describe the solution you'd like**
Use https://github.com/openjdk/jmh

**Describe alternatives you've considered**

**Additional context**

**Comment by asmfstatoil** [comment]
See https://github.com/equinor/neqsim-benchmark

**Comment by EvenSol** [comment]
> See https://github.com/equinor/neqsim-benchmark

This seems like a very good solution. I had problems setting up, but now it work fine. The challenge is how we can use it to see improvements in performance and to use it for finding bottlenecks.

I think using this in combination with the profiler could be good: https://github.com/equinor/neqsim/wiki/Profiling

**Comment by EvenSol** [comment]
Benchmark project created.
