### ISSUE TITLE
bug in release to github packages

### ISSUE THREAD

**Issue by EvenSol** [equinor/neqsim#755]
Wrong name of github package. Currently it makes a release to a package with name: com.equinor.neqsim.neqsim, that should be removed.

**Comment by asmfstatoil** [comment]
<img width="590" alt="image" src="https://github.com/equinor/neqsim/assets/34712686/f3c1226b-88d6-41e2-9061-0e89bf8d6670">
I am not so sure it is a bug. Others does the same, the groupid needs to be unique, so com.equinor won´t do. and the artifact name (i.e., jar files) should be called neqsim-version.jar

What is the issue?
