### ISSUE TITLE
Link to NeqSim .NET repo is broken

### ISSUE THREAD

**Issue by AntonBaluev** [equinor/neqsim#80]
Hello,

On project page https://equinor.github.io/neqsimhome/ link to NeqSim .NET leads to https://github.com/equinor/neqsimcapeopen which is not found (404).

What is the status of NeqSim .NET project? Is it available anywhere? Any plans regarding .Net version?

**Comment by EvenSol** [comment]
Hi - the neqsim project is active. However the NeqSim .Net project is still not available as open source in github.

**Comment by EvenSol** [comment]
I have updated the project page with the information:
The NeqSim .NET toolbox has restricted access.

**Comment by EvenSol** [comment]
Info added in project site.
