### ISSUE TITLE
Invitation link to slack channel

### ISSUE THREAD

**Issue by AntonBaluev** [equinor/neqsim#81]
Invitation link on 
https://github.com/equinor/neqsim/wiki/Getting-started-as-a-NeqSim-developer
is no longer active.

**Comment by EvenSol** [comment]
Thanks for informing. It is a challenge in Slack that this invitation link has a time limit.  I will update.
Even

**Comment by EvenSol** [comment]
Here is the new invitation link:
https://join.slack.com/t/neqsim/shared_invite/enQtODQ1MzE1ODQ5ODYzLTljMThiMDU1YzIyNzBhOWI3ODU2ZGQ0ZjU0ZTRhNjhlODYxYTc4MTU4YWQ5ZTkyYWJiNjY0M2U2NDNiNWFhMWE

**Comment by EvenSol** [comment]
Link updated and should not have a time limit.
