### ISSUE TITLE
:bug: Operations do not converge

### ISSUE THREAD

**Issue by Sviatose** [equinor/neqsim#907]
Water in the dehydrated stream after first run 4.633867677989811 ppm
Water in the dehydrated stream after second run 5.156132446074598 ppm
Water in the dehydrated stream after 5 run 6.4574259175511175 ppm

See GlycolRigTest2

**Comment by Sviatose** [comment]
https://github.com/equinor/neqsim/tree/bug--operations-do-not-converge

**Comment by EvenSol** [comment]
I see for the 
    makeup_calculator.addInputVariable(flash_gas);

you should only add what is not going as strippping gas

**Comment by EvenSol** [comment]
I tried to increase accuracy of recycle - see:
https://github.com/equinor/neqsim/pull/910
