### ISSUE TITLE
Characterize/Lumping similar as PVTsim

### ISSUE THREAD

**Issue by dagm-cyber** [equinor/neqsim#92]
Can you make a LumpingModel that lump in the same way as PVT-sim: keeping C6,..C9 and start lumping from C10.... Also it would be nice to the make names traceable f.eks C13-C15 etc.

**Comment by EvenSol** [comment]
Work is ongoing:
https://github.com/equinor/neqsim/tree/feature/newPVTcharacterization

**Comment by EvenSol** [comment]
Write C10 + for composition to characterized fluid. - solution proposed

**Comment by EvenSol** [comment]
Solution proposed.
To use new characterization set:
fluid1.getCharacterization().setLumpingModel("PVTlumpingModel");
